version: '3.5'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 80
    volumes:
      - /src/node_modules
    environment:
      NODE_ENV: local
      DB_HOST: 0.0.0.0
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: rackoh
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=0.0.0.0
      - POSTGRES_DB=rackoh
    ports:
      - 5432
    volumes:
      - ./db/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
