version: '3.5'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '5000:5000'
    volumes:
      - '.:/src'
      - /src/node_modules
    links:
      - redis
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6380:6379"
