version: '3.5'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '5000:5000'
    volumes:
      - /src/node_modules
    environment:
      NODE_ENV: local
      DB_USER: root
      DB_PASSWORD: root
      DB_DB: rackoh
      DB_HOST: postgres
      DB_PORT: 5432
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rackoh
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - '7000:5432'
    volumes:
      - ./db/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
